-- P1 launch-hardening migration.
-- Run in Supabase SQL Editor before treating rate limiting as active.

create unique index if not exists bookings_unique_active_slot
  on public.bookings (lesson_date, lesson_time)
  where status <> 'cancelled';

create table if not exists public.rate_limit_events (
  id bigint generated by default as identity primary key,
  route text not null,
  ip_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists rate_limit_events_route_ip_created_idx
  on public.rate_limit_events (route, ip_hash, created_at desc);

alter table public.rate_limit_events enable row level security;

-- No public policies are expected for rate_limit_events.
-- The Next.js server records and reads events using the Supabase service role.

-- Optional cleanup for old rows. Run periodically if this table grows.
-- delete from public.rate_limit_events where created_at < now() - interval '7 days';
